"""
==========================================================================
CoQuí: Correlated Quantum ínterface

Copyright (c) 2022-2026 Simons Foundation & The CoQuí developer team

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
==========================================================================
"""

from mpi4py import MPI
import pytest
import os
import numpy as np
import tempfile
from h5 import HDFArchive

import coqui
from coqui.utils.imag_axes_ft import IAFT


def ir_filename(lmbda: float, prec: float):
    if lmbda == 100:
        lmbda_str = "1e2"
    elif lmbda == 1000:
        lmbda_str = "1e3"
    elif lmbda == 10000:
        lmbda_str = "1e4"
    elif lmbda == 100000:
        lmbda_str = "1e5"
    elif lmbda == 1000000:
        lmbda_str = "1e6"
    else:
        raise ValueError("Unsupported lambda value")

    if prec == 1e-6:
        prec_str = "1e-06"
    elif prec == 1e-10:
        prec_str = "1e-10"
    elif prec == 1e-15:
        prec_str = "1e-15"
    else:
        raise ValueError("Unsupported precision value")

    filename = coqui.INSTALL_DIR+"/data/ir/"+lmbda_str+"."+prec_str+".h5"
    if os.path.isfile(filename):
        return filename

    filename = coqui.PROJECT_SOURCE_DIR+"/src/numerics/imag_axes_ft/ir/data/ir/" + lmbda_str + "." + prec_str + ".h5"
    if os.path.isfile(filename):
        return filename

    raise FileNotFoundError(f"IR data file not found for lambda={lmbda}, prec={prec}")


def compare_sparse_ir_h5(wmax: float, prec: str):
    """
    Compare the IR basis generated by sparse_ir with the precomputed basis stored in the HDF5 file.
    This check ensures compatibility of sparse_ir across different library versions.

    :param wmax: frequency cutoff
    :param prec: "low" (1e-6), "medium" (1e-10), "high" (1e-15)
    """
    ir = IAFT(beta=1.0, wmax=wmax, prec=prec, basis='ir')
    with HDFArchive(ir_filename(ir.lmbda, ir.eps), "r") as ar:
        tau_mesh = ar["fermion"]["tau_mesh"]
        wn_mesh = ar["fermion"]["wn_mesh"]
        assert np.allclose(tau_mesh, ir.tau_mesh(stats="f", rel_notation=True), atol=1e-12)
        assert np.allclose(wn_mesh, ir.wn_mesh(stats='f'), atol=1e-12)

        tau_mesh = ar["boson"]["tau_mesh"]
        wn_mesh = ar["boson"]["wn_mesh"]
        assert np.allclose(tau_mesh, ir.tau_mesh(stats="b", rel_notation=True), atol=1e-12)
        assert np.allclose(wn_mesh, ir.wn_mesh(stats='b'), atol=1e-12)

        Ttw = ar["fermion"]["Ttw"] * np.sqrt(2)
        Twt = ar["fermion"]["Twt"] / np.sqrt(2)
        assert np.allclose(Ttw, ir.Ttw_ff, atol=1e-12)
        assert np.allclose(Twt, ir.Twt_ff, atol=1e-12)

        Ttw = ar["boson"]["Ttw"] * np.sqrt(2)
        Twt = ar["boson"]["Twt"] / np.sqrt(2)
        assert np.allclose(Ttw, ir.Ttw_bb, atol=1e-12)
        assert np.allclose(Twt, ir.Twt_bb, atol=1e-12)



def test_ir_compatibility():
    wmax_list = [90.0, 900.0, 9000.0, 90000.0]
    for wmax in wmax_list:
        compare_sparse_ir_h5(wmax=wmax, prec="low")
        compare_sparse_ir_h5(wmax=wmax, prec="medium")
        compare_sparse_ir_h5(wmax=wmax, prec="high")


@pytest.mark.parametrize("stats,ph_sym,basis", [
    ('f', False, "dlr"),
    ('b', False, "dlr"),
    ('b', True, "dlr"),
    ('f', False, "ir"),
    ('b', False, "ir"),
    ('b', True, "ir"),
])
def test_fourier_transform(stats, ph_sym, basis):
    """G(tau) and G(iw) returned by the two builders should be consistent via IAFT."""
    if basis == "dlr":
        pytest.importorskip("coqui._lib.iaft_module")
    norb = 2
    beta = 5.0
    iaft = IAFT(beta=beta, wmax=100.0, prec="high", basis=basis)

    G_tau_ref = iaft.build_g_tau_ref(norb, stats, ph_sym)  # shape (nt_f, norb, norb)
    G_iw_ref = iaft.build_g_iw_ref(norb, stats, ph_sym)  # shape (nw_f, norb, norb)

    G_iw_computed = iaft.tau_to_w(G_tau_ref, stats=stats, ph_sym=ph_sym)
    G_tau_computed = iaft.w_to_tau(G_iw_ref, stats=stats, ph_sym=ph_sym)

    assert np.allclose(G_iw_computed, G_iw_ref, atol=1e-8), (
        f"Max deviation: {np.max(np.abs(G_iw_computed - G_iw_ref))}"
    )
    assert np.allclose(G_tau_computed, G_tau_ref, atol=1e-8), (
        f"Max deviation: {np.max(np.abs(G_tau_computed - G_tau_ref))}"
    )

    # tau interpolation
    iaft_interp = IAFT(beta=beta, wmax=10.0, prec="high", basis=basis)
    G_tau_interp_ref = iaft_interp.build_g_tau_ref(norb, stats, ph_sym)  # shape (nt_f, norb, norb)
    G_tau_interp = iaft.tau_interpolate(G_tau_ref, iaft_interp, stats, ph_sym=ph_sym)

    assert np.allclose(G_tau_interp, G_tau_interp_ref, atol=1e-8), (
        f"Max deviation: {np.max(np.abs(G_tau_interp - G_tau_interp_ref))}"
    )

    # iw interpolation
    G_iw_interp_ref = iaft_interp.build_g_iw_ref(norb, stats, ph_sym)  # shape (nw_interp, norb, norb)
    G_iw_interp = iaft.w_interpolate(G_iw_ref, iaft_interp, stats, ph_sym=ph_sym)

    assert np.allclose(G_iw_interp, G_iw_interp_ref, atol=1e-8), (
        f"Max deviation: {np.max(np.abs(G_iw_interp - G_iw_interp_ref))}"
    )

    # Test the old API for ph-symmetric case
    if ph_sym:
        G_iw_computed = iaft.tau_to_w_phsym(G_tau_ref, stats=stats)
        G_tau_computed = iaft.w_to_tau_phsym(G_iw_ref, stats=stats)
        assert np.allclose(G_iw_computed, G_iw_ref, atol=1e-8), (
            f"Max deviation: {np.max(np.abs(G_iw_computed - G_iw_ref))}"
        )
        assert np.allclose(G_tau_computed, G_tau_ref, atol=1e-8), (
            f"Max deviation: {np.max(np.abs(G_tau_computed - G_tau_ref))}"
        )

        G_tau_interp = iaft.tau_interpolate_phsym(G_tau_ref, iaft_interp, stats)
        assert np.allclose(G_tau_interp, G_tau_interp_ref, atol=1e-8), (
            f"Max deviation: {np.max(np.abs(G_tau_interp - G_tau_interp_ref))}"
        ) 
        G_iw_interp = iaft.w_interpolate_phsym(G_iw_ref, iaft_interp, stats)
        assert np.allclose(G_iw_interp, G_iw_interp_ref, atol=1e-8), (
            f"Max deviation: {np.max(np.abs(G_iw_interp - G_iw_interp_ref))}"
        )


@pytest.mark.parametrize("basis", [
    ("dlr"),
    ("ir"),
])
def test_iaft_requires_at_least_one_accuracy_arg(basis):
    with pytest.raises(ValueError, match="at least one of 'prec' or 'eps'"):
        IAFT(beta=5.0, wmax=10.0, prec=None, eps=None, basis=basis)

@pytest.mark.parametrize("basis", [
    ("dlr"),
    ("ir"),
])
def test_iaft_prefers_prec_when_both_and_prec_not_custom(basis):
    iaft = IAFT(beta=5.0, wmax=10.0, prec="low", eps=1e-11, basis=basis, verbose=False)
    assert iaft.prec == "low"
    assert iaft.eps == pytest.approx(1e-6)


# meaning that "custom" is redundant when eps is provided. 
@pytest.mark.parametrize("basis", [
    ("dlr"),
    ("ir"),
])
def test_iaft_prefers_eps_when_both_and_prec_custom(basis):
    iaft = IAFT(beta=5.0, wmax=10.0, prec="custom", eps=3e-4, basis=basis, verbose=False)
    assert iaft.prec == "custom"
    assert iaft.eps == pytest.approx(3e-4)

@pytest.mark.parametrize("basis", [
    ("dlr"),
    ("ir"),
])
def test_iaft_accepts_eps_and_roundtrips_checkpoint(basis):
    iaft = IAFT(beta=5.0, wmax=10.0, prec=None, eps=1e-4, basis=basis, verbose=False)
    assert iaft.prec == "custom"
    assert iaft.eps == pytest.approx(1e-4)

    with tempfile.TemporaryDirectory() as tmpdir:
        chkpt = os.path.join(tmpdir, "iaft_test.h5")
        with HDFArchive(chkpt, 'w') as ar:
            iaft.save(ar)

        with HDFArchive(chkpt, 'r') as ar:
            iaft_grp = ar['imaginary_fourier_transform']
            assert iaft_grp['basis'] == basis

        restored = IAFT.from_coqui_chkpt(chkpt, verbose=False)
        assert restored == iaft
        assert restored.eps == pytest.approx(1e-4)
        assert restored.prec == "custom"


def test_iaft_restores_from_ir_checkpoint():
    # This test checks that the old checkpoint format with "source" field is still compatible. 
    with tempfile.TemporaryDirectory() as tmpdir:
        chkpt = os.path.join(tmpdir, "iaft_legacy_source.h5")
        with HDFArchive(chkpt, 'w') as ar:
            ar.create_group('imaginary_fourier_transform')
            iaft_grp = ar['imaginary_fourier_transform']
            iaft_grp['beta'] = 5.0
            iaft_grp['wmax'] = 10.0
            iaft_grp['prec'] = 'low'
            iaft_grp['source'] = 'ir'

        restored = IAFT.from_coqui_chkpt(chkpt, verbose=False)
        assert restored.beta == pytest.approx(5.0)
        # Since IR basis was pre-generated with a set of lambda values, IAFT with IR backend will 
        # on-the-fly determine the most appropriate lambda and recalculate wmax based on the lambda 
        # and beta. Therefore, restored.wmax should not be 10.0 as in the checkpoint, but rather 
        # wmax = 20.0 corresponding to lambda = 100.0 and beta=5.0.
        assert restored.wmax == pytest.approx(20.0)
        assert restored.prec == 'low'
        assert restored.basis == 'ir'

@pytest.mark.parametrize("basis", [
    ("dlr"),
    ("ir"),
])
def test_tau_notation(basis):
    iaft = IAFT(beta=5.0, wmax=10.0, prec="low", basis=basis)
    # by default, tau_mesh should be in physical notation
    taus_abs = iaft.tau_mesh('f')
    assert np.all(taus_abs >= 0) and np.all(taus_abs <= iaft.beta)

    # if rel_notation=True, tau_mesh should be in [-1, 1] 
    taus_rel = iaft.tau_mesh('f', rel_notation=True)
    assert np.all(taus_rel >= -1) and np.all(taus_rel <= 1)

    # by default, tau_interpolate interprets tau points in physical notation
    G_tau = iaft.build_g_tau_ref(2, 'f', ph_sym=False)
    Dm_abs = -1.0 * iaft.tau_interpolate(G_tau, iaft.beta, 'f')
    Dm_rel = -1.0 * iaft.tau_interpolate(G_tau, 1.0, 'f', rel_notation=True)
    assert np.allclose(Dm_abs, Dm_rel, atol=1e-12)


@pytest.mark.parametrize("basis", [
    ("dlr"),
    ("ir"),
])
def test_iaft_mesh_roundtrip_through_checkpoint(basis):
    """save() must record the meshes in exactly the layout and conventions
    chkpt_utils.cpp uses - tau on the rescaled [-1, 1] axis, wn as the CoQui odd/even
    integer index - so that both the C++ read_iaft and from_coqui_chkpt can validate a
    rebuilt grid against them. A checkpoint we just wrote must then load back cleanly."""
    iaft = IAFT(beta=5.0, wmax=10.0, prec="high", basis=basis, verbose=False)

    with tempfile.TemporaryDirectory() as tmpdir:
        chkpt = os.path.join(tmpdir, "iaft_mesh.h5")
        with HDFArchive(chkpt, 'w') as ar:
            iaft.save(ar)

        with HDFArchive(chkpt, 'r') as ar:
            grp = ar['imaginary_fourier_transform']
            np.testing.assert_allclose(grp['tau_mesh']['fermion'],
                                       iaft.tau_mesh('f', rel_notation=True))
            np.testing.assert_allclose(grp['tau_mesh']['boson'],
                                       iaft.tau_mesh('b', rel_notation=True))
            np.testing.assert_array_equal(grp['iwn_mesh']['fermion'], iaft.wn_mesh('f'))
            np.testing.assert_array_equal(grp['iwn_mesh']['boson'], iaft.wn_mesh('b'))

        # the grid validation in from_coqui_chkpt must accept what save() just wrote
        restored = IAFT.from_coqui_chkpt(chkpt, verbose=False)
        assert restored == iaft


def test_from_coqui_chkpt_rejects_mismatched_grid():
    """A checkpoint whose stored mesh disagrees with the grid rebuilt from its own
    scalar metadata cannot be reinterpreted on that grid, so the load must fail loudly
    instead of silently handing back an IAFT on the wrong nodes."""
    with tempfile.TemporaryDirectory() as tmpdir:
        chkpt = os.path.join(tmpdir, "iaft_bad_mesh.h5")
        with HDFArchive(chkpt, 'w') as ar:
            ar.create_group('imaginary_fourier_transform')
            grp = ar['imaginary_fourier_transform']
            grp['beta'] = 5.0
            grp['wmax'] = 10.0
            grp['prec'] = 'high'
            grp['basis'] = 'dlr'
            grp.create_group('tau_mesh')
            grp['tau_mesh']['fermion'] = np.array([-1.0, 0.0, 1.0])
            grp['tau_mesh']['boson'] = np.array([-1.0, 0.0, 1.0])

        with pytest.raises(ValueError, match="tau_mesh"):
            IAFT.from_coqui_chkpt(chkpt, verbose=False)


def test_from_coqui_chkpt_without_meshes_still_loads():
    """Old checkpoints that do not contain the meshes must still load."""
    with tempfile.TemporaryDirectory() as tmpdir:
        chkpt = os.path.join(tmpdir, "iaft_no_mesh.h5")
        with HDFArchive(chkpt, 'w') as ar:
            ar.create_group('imaginary_fourier_transform')
            grp = ar['imaginary_fourier_transform']
            grp['beta'] = 5.0
            grp['wmax'] = 10.0
            grp['prec'] = 'high'
            grp['basis'] = 'dlr'

        restored = IAFT.from_coqui_chkpt(chkpt, verbose=False)
        assert restored.beta == pytest.approx(5.0)
